// Generated by gencpp from file learning_service/person.msg
// DO NOT EDIT!


#ifndef LEARNING_SERVICE_MESSAGE_PERSON_H
#define LEARNING_SERVICE_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <learning_service/personRequest.h>
#include <learning_service/personResponse.h>


namespace learning_service
{

struct person
{

typedef personRequest Request;
typedef personResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct person
} // namespace learning_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_service::person > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::learning_service::person&) { return value(); }
};

template<>
struct DataType< ::learning_service::person > {
  static const char* value()
  {
    return "learning_service/person";
  }

  static const char* value(const ::learning_service::person&) { return value(); }
};


// service_traits::MD5Sum< ::learning_service::personRequest> should match
// service_traits::MD5Sum< ::learning_service::person >
template<>
struct MD5Sum< ::learning_service::personRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_service::person >::value();
  }
  static const char* value(const ::learning_service::personRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_service::personRequest> should match
// service_traits::DataType< ::learning_service::person >
template<>
struct DataType< ::learning_service::personRequest>
{
  static const char* value()
  {
    return DataType< ::learning_service::person >::value();
  }
  static const char* value(const ::learning_service::personRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_service::personResponse> should match
// service_traits::MD5Sum< ::learning_service::person >
template<>
struct MD5Sum< ::learning_service::personResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_service::person >::value();
  }
  static const char* value(const ::learning_service::personResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_service::personResponse> should match
// service_traits::DataType< ::learning_service::person >
template<>
struct DataType< ::learning_service::personResponse>
{
  static const char* value()
  {
    return DataType< ::learning_service::person >::value();
  }
  static const char* value(const ::learning_service::personResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_SERVICE_MESSAGE_PERSON_H
